/*jslint node: true, nomen: true */
"use strict";

exports.createEvents = function (options) {
    return {
        'on-change-campaign-state-result': require('./on-change-campaign-state-result').createEvent(options)
        ,'go-to-images-upload': require('./go-to-images-upload').createEvent(options)
        ,'go-to-workers': require('./go-to-workers').createEvent(options)
        ,'login-btn-pressed': require('./login-btn-pressed').createEvent(options)
        ,'register-btn-pressed': require('./register-btn-pressed').createEvent(options)
        ,'logout-btn-pressed': require('./logout-btn-pressed').createEvent(options)
        ,'account-edit-btn-pressed': require('./account-edit-btn-pressed').createEvent(options)
        ,'go-manager-campaign-image': require('./go-manager-campaign-image').createEvent(options)
        ,'create-campaign-btn-pressed': require('./create-campaign-btn-pressed').createEvent(options)
        ,'go-edit-campaign': require('./go-edit-campaign').createEvent(options)
        ,'change-state-campaign': require('./change-state-campaign').createEvent(options)
        ,'on-account-edit-failure': require('./on-account-edit-failure').createEvent(options)
        ,'on-account-edit-success': require('./on-account-edit-success').createEvent(options)
        ,'on-create-campaign-failure': require('./on-create-campaign-failure').createEvent(options)
        ,'on-create-campaign-success': require('./on-create-campaign-success').createEvent(options)
        ,'on-edit-campaign-success': require('./on-edit-campaign-success').createEvent(options)
        ,'on-edit-campaign-failure': require('./on-edit-campaign-failure').createEvent(options)
        ,'on-more-image-to-selected': require('./on-more-image-to-selected').createEvent(options)
        ,'on-no-more-images-to-select': require('./on-no-more-images-to-select').createEvent(options)
        ,'on-image-upload-failure': require('./on-image-upload-failure').createEvent(options)
        ,'on-image-upload-success': require('./on-image-upload-success').createEvent(options)
        ,'on-more-images-to-annotate': require('./on-more-images-to-annotate').createEvent(options)
        ,'on-no-more-images-annotate': require('./on-no-more-images-annotate').createEvent(options)
        ,'on-logout-success': require('./on-logout-success').createEvent(options)
        ,'go-manager-campaign': require('./go-manager-campaign').createEvent(options)
        ,'on-account-edit-submit': require('./on-account-edit-submit').createEvent(options)
        ,'on-create-campaign-submit': require('./on-create-campaign-submit').createEvent(options)
        ,'7d7aa24d-b606-4a4d-95b6-e026635228e0': require('./7d7aa24d-b606-4a4d-95b6-e026635228e0').createEvent(options)
        ,'on-image-annotation-submit': require('./on-image-annotation-submit').createEvent(options)
        ,'on-image-selection-submit': require('./on-image-selection-submit').createEvent(options)
        ,'on-image-upload-submit': require('./on-image-upload-submit').createEvent(options)
        ,'on-login-submit': require('./on-login-submit').createEvent(options)
        ,'496ca6e1-d56b-4d3d-9567-ca80fbeeb9e5': require('./496ca6e1-d56b-4d3d-9567-ca80fbeeb9e5').createEvent(options)
        ,'on-register-submit': require('./on-register-submit').createEvent(options)
        ,'go-to-image-selection': require('./go-to-image-selection').createEvent(options)
        ,'go-to-image-annotation': require('./go-to-image-annotation').createEvent(options)
        ,'2c13eb15-2680-4393-a576-b5f2cc847b95': require('./2c13eb15-2680-4393-a576-b5f2cc847b95').createEvent(options)
        ,'d80e9591-d019-4eb7-b1f3-205377663d62': require('./d80e9591-d019-4eb7-b1f3-205377663d62').createEvent(options)
        ,'on-send-worker-success': require('./on-send-worker-success').createEvent(options)
        ,'on-send-annotator-success': require('./on-send-annotator-success').createEvent(options)
        ,'on-login-worker-success': require('./on-login-worker-success').createEvent(options)
        ,'on-login-failure': require('./on-login-failure').createEvent(options)
        ,'on-login-manager-success': require('./on-login-manager-success').createEvent(options)
        ,'on-registration-failure': require('./on-registration-failure').createEvent(options)
        ,'on-registration-worker-success': require('./on-registration-worker-success').createEvent(options)
        ,'on-registration-manager-success': require('./on-registration-manager-success').createEvent(options)
    };
};
